# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MIDAS
                                 A QGIS plugin
 Memory-Efficient I/O-Improved Drainage Analysis System
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-26
        copyright            : (C) 2025 by Huidae Cho
        email                : grass4u@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Huidae Cho'
__date__ = '2025-07-26'
__copyright__ = '(C) 2025 by Huidae Cho'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MIDAS class from file MIDAS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .midas import MIDASPlugin
    return MIDASPlugin()
